In [5]:
import re
"""
Getting the meta data in a list and the real words, pos tags, and lemmas in another list
"""
meta_data = []
stories = []
stop_chars = ['<', '>']
with open("test.txt") as infile:
        for line in infile:
            l = line.rstrip()
            if "<text" in l:
                meta_data.append(l)
            if l == "<story>":
                story = []
#                 for i in meta_data:
#                     text_id = re.search(r'id="([^"]+)"', i).group(1)
#                     story.append(text_id)
            elif l == "</story>":
                stories.append(story)
            elif not any(stop_char in l for stop_char in stop_chars):
                story.append(l)
                
            

print(meta_data)
stories[0]

['<text id="t__f326ea56_b0ee_11e5_8db1_5749827613a1" collection="Communication Studies Archive, UCLA" file="/db/tv/2016/2016-01/2016-01-01/2016-01-01_2359_US_WKYC_Channel_3_News_at_7.txt" date="2016-01-01" year="2016" month="01" day="01" time="2359" duration="0:30:01.001" country="US" channel="WKYC" title="Channel 3 News at 7" video_resolution="480x360" video_resolution_original="" language="ENG" recording_location="CWRU Cleveland cmm" original_broadcast_date="N/A" original_broadcast_time="N/A" original_broadcast_timezone="N/A" local_broadcast_date="2016-01-01" local_broadcast_time="18:59" local_broadcast_timezone="America/New_York">']

['Family\tNN\tfamily',
 'members\tNNS\tmember',
 'are\tVBP\tbe',
 'responding\tVBG\trespond',
 'tonight\tNN\ttonight',
 ',\t,\t,',
 'plus\tCC\tplus',
 '.\t.\t.',
 'You\tPRP\tyou',
 'know\tVBP\tknow',
 'what\tWP\twhat',
 'I\tPRP\tI',
 'was\tVBD\tbe',
 'thinking\tVBG\tthink',
 'since\tIN\tsince',
 'we\tPRP\twe',
 'got\tVBD\tget',
 'the\tDT\tthe',
 'casinos\tNNS\tcasino',
 ',\t,\t,',
 'will\tMD\twill',
 'throw\tVB\tthrow',
 '$\t$\t$',
 '20\tCD\t20',
 'in\tIN\tin',
 'the\tDT\tthe',
 'machines\tNNS\tmachine',
 'and\tCC\tand',
 'I\tPRP\tI',
 '&apos;ll\tMD\twill',
 'see\tVB\tsee',
 'what\tWP\twhat',
 'happens\tVBZ\thappen',
 '.\t.\t.',
 'Why\tWRB\twhy',
 'a\tDT\ta',
 'new\tJJ\tnew',
 'mom\tNN\tmom',
 'is\tVBZ\tbe',
 'feeling\tVBG\tfeel',
 'extra\tJJ\textra',
 'lucky\tJJ\tlucky',
 'thanks\tNNS\tthanks',
 'to\tTO\tto',
 'her\tPRP$\tshe',
 'New\tJJ\tnew',
 'Year\tNN\tyear',
 '&apos;s\tPOS\t&apos;s',
 'baby\tNN\tbaby',
 '.\t.\t.']

In [14]:
"""
Building a column for each text-unit in the <text> tag
"""

import xml.etree.ElementTree as ET
import pandas as pd

id_ = [] #keeping the ids in a list so that they can be added later into the other table with words and lemmas of the stories

#id_, collection, file, date, year, month, day, time, duration, country, channel, title, video_resolution, video_resolution_original, language, recording_location, original_broadcast_date, original_broadcast_time, original_broadcast_timezone, local_broadcast_date, local_broadcast_time, local_broadcast_timezone = [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []

cols = ["id", "collection", "file", "date", "year", "month", "day", "time", "duration", "country", "channel", "title", "video_resolution", "video_resolution_original", "language", "recording_location", "original_broadcast_date", "original_broadcast_time", "original_broadcast_timezone", "local_broadcast_date", "local_broadcast_time", "local_broadcast_timezone" ]

data = []

In [15]:
"""
Building a dataframe where each text-unit is a column
"""

for string in meta_data:
    row = []
    tree = ET.fromstring(string+"</text>") #corrects wrong format

    id_.append(tree.get("id")) #1 ##keeping the ids in a list so that they can be added later into the other table with words and lemmas of the stories

#     collection.append(tree.get("collection")) 
#     file.append(tree.get("file"))
#     date.append(tree.get("date"))
#     year.append(tree.get("year")) #5
#     month.append(tree.get("month")) 
#     day.append(tree.get("day"))
#     time.append(tree.get("time"))
#     duration.append(tree.get("duration"))
#     country.append(tree.get("country")) #10
#     channel.append(tree.get("channel")) 
#     title.append(tree.get("title"))
#     video_resolution.append(tree.get("video_resolution"))
#     video_resolution_original.append(tree.get("video_resolution_original"))
#     language.append(tree.get("language")) #15
#     recording_location.append(tree.get("recording_location")) 
#     original_broadcast_date.append(tree.get("original_broadcast_date"))
#     original_broadcast_time.append(tree.get("original_broadcast_time"))
#     original_broadcast_timezone.append(tree.get("original_broadcast_timezone"))
#     local_broadcast_date.append(tree.get("local_broadcast_date")) #20
#     local_broadcast_time.append(tree.get("local_broadcast_time"))
#     local_broadcast_timezone.append(tree.get("local_broadcast_timezone"))
    for col in cols:
        row.append(tree.get(col))
    data.append(row)

df_meta_data = pd.DataFrame(data,columns=cols)
df_meta_data

# print(id_, collection, file, date, year, month, day, time, duration, country, channel, title,
#       video_resolution, video_resolution_original, language, recording_location, original_broadcast_date,
#       original_broadcast_time, original_broadcast_timezone, local_broadcast_date, local_broadcast_time,
#       local_broadcast_timezone)

,id,collection,file,date,year,month,day,time,duration,country,...,video_resolution,video_resolution_original,language,recording_location,original_broadcast_date,original_broadcast_time,original_broadcast_timezone,local_broadcast_date,local_broadcast_time,local_broadcast_timezone
0,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"Communication Studies Archive, UCLA",/db/tv/2016/2016-01/2016-01-01/2016-01-01_2359...,2016-01-01,2016,01,01,2359,0:30:01.001,US,...,480x360,,ENG,CWRU Cleveland cmm,N/A,N/A,N/A,2016-01-01,18:59,America/New_York

In [18]:
#stories
#story

In [8]:
import re
#real_words, pos_tags, lemmas = [], [], []

"""
Using re.search to find and separate real_words, pos_tags, and lemmas and then reconstruct them into list of lists where 
each sublist contains all the real_words, pos_tags, and lemmas of each story 
"""
real_words = [[re.search(r'(.*)\t(.*)\t(.*)', i).group(1) for i in j] for j in stories]
story_itself = [[' '.join(i)] for i in real_words] # Building the story in a human readable format
#print(story[3])

pos_tags = [[re.search(r'(.*)\t(.*)\t(.*)', i).group(2) for i in j] for j in stories]
lemmas = [[re.search(r'(.*)\t(.*)\t(.*)', i).group(3) for i in j] for j in stories]

In [11]:
cols_for_stories = ["id", "real_words", "story_itself", "pos_tags", "lemmas"]

In [12]:
df_stories = pd.DataFrame({'id':id_*len(real_words),'real_words':real_words, 'story_itself':story_itself, 'pos_tags':pos_tags, 'lemmas':lemmas}, columns=cols_for_stories)
df_stories

,id,real_words,story_itself,pos_tags,lemmas
0,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[Family, members, are, responding, tonight, ,,...","[Family members are responding tonight , plus ...","[NN, NNS, VBP, VBG, NN, ,, CC, ., PRP, VBP, WP...","[family, member, be, respond, tonight, ,, plus..."
1,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[Happy, New, Year, and, thanks, for, joining, ...",[Happy New Year and thanks for joining us . Ji...,"[JJ, JJ, NN, CC, NNS, IN, VBG, PRP, ., NNP, VB...","[happy, new, year, and, thanks, for, join, we,..."
2,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[And, it, &apos;s, not, only, a, new, year, bu...",[And it &apos;s not only a new year but a new ...,"[CC, PRP, VBZ, RB, RB, DT, JJ, NN, CC, DT, JJ,...","[and, it, be, not, only, a, new, year, but, a,..."
3,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[Ohio, state, and, Notre, Dame, met, in, the, ...",[Ohio state and Notre Dame met in the fiesta b...,"[NNP, NNP, CC, NNP, NNP, VBD, IN, DT, NNP, NNP...","[Ohio, state, and, Notre, Dame, meet, in, the,..."
4,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[A, group, of, protesters, hopeed, the, New, Y...",[A group of protesters hopeed the New Year wou...,"[DT, NN, IN, NNS, VBD, DT, JJ, NN, MD, VB, NN,...","[a, group, of, protester, hopeed, the, new, ye..."
5,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[Now, that, the, temperature, is, watching, .,...",[Now that the temperature is watching . Local ...,"[RB, IN, DT, NN, VBZ, VBG, ., JJ, NN, NNS, MD,...","[now, that, the, temperature, be, watch, ., lo..."
6,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[I, &apos;m, excited, ,, we, &apos;re, making,...","[I &apos;m excited , we &apos;re making record...","[PRP, VBP, JJ, ,, PRP, VBP, VBG, NNS, RB, CC, ...","[I, be, excited, ,, we, be, make, record, alre..."
7,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[Keeping, Cleveland, warm, ., The, great, new,...",[Keeping Cleveland warm . The great new idea t...,"[VBG, NNP, JJ, ., DT, JJ, JJ, NN, IN, NNS, NNS...","[keep, Cleveland, warm, ., the, great, new, id..."
8,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[Plus, Rocket, Revolution, ., How, we, &apos;r...",[Plus Rocket Revolution . How we &apos;re now ...,"[CC, NN, NN, ., WRB, PRP, VBP, RB, CD, NN, RBR...","[plus, rocket, revolution, ., how, we, be, now..."
9,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[There, &apos;s, a, new, activity, that, &apos...",[There &apos;s a new activity that &apos;S GRO...,"[EX, VBZ, DT, JJ, NN, WDT, VBZ, VBG, RBR, JJ, ...","[there, be, a, new, activity, that, be, grow, ..."
10,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[Still, to, come, ,, Sky, High, Game, ., The, ...","[Still to come , Sky High Game . The ambitious...","[RB, TO, VB, ,, NNP, JJ, NN, ., DT, JJ, NN, WD...","[still, to, come, ,, Sky, high, game, ., the, ..."
11,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[And, how, low, the, thermometer, will, go, .,...",[And how low the thermometer will go . These s...,"[CC, WRB, JJ, DT, NN, MD, VB, ., DT, NNS, MD, ...","[and, how, low, the, thermometer, will, go, .,..."
12,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[Well, space, travel, is, getting, a, boost, t...",[Well space travel is getting a boost thanks t...,"[RB, NN, NN, VBZ, VBG, DT, NN, NNS, TO, VB, VB...","[well, space, travel, be, get, a, boost, thank..."
13,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[If, eating, healthier, is, one, of, your, New...",[If eating healthier is one of your New Year &...,"[IN, NN, RBR, VBZ, CD, IN, PRP$, JJ, NN, POS, ...","[if, eating, healthier, be, one, of, you, new,..."
14,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[What, if, you, mix, good, year, with, corn, h...",[What if you mix good year with corn hole . Go...,"[WP, IN, PRP, VBP, JJ, NN, IN, NN, NN, ., JJ, ...","[what, if, you, mix, good, year, with, corn, h..."
15,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[What, do, you, promise, to, change, for, the,...",[What do you promise to change for the New Yea...,"[WP, VBP, PRP, VBP, TO, VB, IN, DT, JJ, NN, .,...","[what, do, you, promise, to, change, for, the,..."
16,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[It, is, a, new, year, and, a, time, when, man...",[It is a new year and a time when many people ...,"[PRP, VBZ, DT, JJ, NN, CC, DT, NN, WRB, JJ, NN...","[it, be, a, new, year, and, a, time, when, man..."
17,t__f326ea56_b0ee_11e5_8db1_5749827613a1,"[And, we, also, got, comments, ,, Jennifer, sa...","[And we also got comments , Jennifer says less...","[CC, PRP, RB, VBD, NNS, ,, NNP, VBZ, RBR, NN, ...","[and, we, also, get, comment, ,, Jennifer, say..."

In [ ]:
df_meta_data.to_csv("test_one_file_metadata.csv")
df_stories.to_csv("test_one_file_stories.csv")

In [17]:
import sqlite3
cnx = sqlite3.connect('one_file_stories.db')
df = pd.read_csv('test_one_file_stories.csv')
df.to_sql('one_file_stories', cnx)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pandas/core/generic.py:1362: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  chunksize=chunksize, dtype=dtype)