In [147]:
#from nltk.tokenize import RegexpTokenizer
from gensim import corpora, models
from gensim.models import Phrases
#from sklearn import decomposition
#import pyLDAvis.gensim as gensimvis
#import pyLDAvis
#import pandas as pd
#import numpy as np
#import re

# initialize tokenizer and stopwords
en_stop = ['a', 'about', 'above', 'after', 'again', 'against', 'all', 'am', 'an', 'and', 'any', 'are', "aren't", 'as',
           'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', "can't", 'cannot',
           'could', "couldn't", 'did', "didn't", 'do', 'does', "doesn't", 'doing', "don't", 'down', 'during', 'each',
           'few', 'for', 'from', 'further', 'had', "hadn't", 'has', "hasn't", 'have', "haven't", 'having', 'he', "he'd",
           "he'll", "he's", 'her', 'here', "here's", 'hers', 'herself', 'him', 'himself', 'his', 'how', "how's", 'i', "i'd",
           "i'll", "i'm", "i've", 'if', 'in', 'into', 'is', "isn't", 'it', "it's", 'its', 'itself', "let's", 'me', 'more',
           'most', "mustn't", 'my', 'myself', 'no', 'nor', 'not', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'ought',
           'our', 'ours', 'ourselves', 'out', 'over', 'own', 'same', "shan't", 'she', "she'd", "she'll", "she's", 'should',
           "shouldn't", 'so', 'some', 'such', 'than', 'that', "that's", 'the', 'their', 'theirs', 'them', 'themselves', 'then',
           'there', "there's", 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to',
           'too', 'under', 'until', 'up', 'very', 'was', "wasn't", 'we', "we'd", "we'll", "we're", "we've", 'were', "weren't",
           'what', "what's", 'when', "when's", 'where', "where's", 'which', 'while', 'who', "who's", 'whom', 'why', "why's",
           'with', "won't", 'would', "wouldn't", 'you', "you'd", "you'll", "you're", "you've", 'your', 'yours', 'yourself',
           'yourselves', 'apos', '&apos;m', '&apos;re', '&apos;s', 's', 'I', 'will', 'go', 'get', '(', ')', '?', ':', ';', ',', '.', '!',
           '/', '"', "'", "...","``", "&apos", "&apos;s", "&apos;&apos;", "-lsb-", "-rsb-", "-lcb-", "-rcb-", "-lrb-", "-rrb-",
            "--", " "]
en_stop_stories = ['(', ')', '?', ':', ';', ',', '.', '!', '/', '"', "'", "...","``", "-lsb-", "-rsb-", "-lcb-", "-rcb-", "-lrb-", "-rrb-", "--", " "]

stop_chars = ['<', '>', '.']

# get all lemmas between a <story>-</story>-pair:
stories = []
lemma_stories = []
stop_chars = ['<', '>']
for line in open('1-2-3_story_test.txt'):
    l = line.rstrip()
    #print(l)
    if l == "<story>":
        story = []
        #print(story)
    elif l == "</story>":
        stories.append(story)
    elif not any(stop_char in l for stop_char in stop_chars):
        story.append(l)
#print(stories)

In [32]:
x = stories
y = lemma_stories

In [148]:
# create dictionary and wordcounts corpus:
dictionary = corpora.Dictionary(lemma_stories)
#print(dictionary.token2id)
dictionary.save("wordcounts.dict")

print(len(dictionary))


# Bag-of-words representation of the stories.
corpus = [dictionary.doc2bow(story) for story in lemma_stories]
#print(corpus)
#corpora.MmCorpus.serialize("corpus.mm", corpus)
print(len(corpus))
print(len(stories))
print(len(lemma_stories))

3045
28
28
28

In [149]:
# create tf.idf model:
tfidf_model = models.TfidfModel(corpus)
#tfidf_model.save("tfidf_model")
tfidf_corpus = tfidf_model[corpus]
print(tfidf_corpus)
print(tfidf_corpus.chunksize)
# corpora.MmCorpus.serialize("tfidf_corpus.mm", tfidf_corpus)
#
# # create topic models:
# LDA
num_topics = 50

lda_model = models.ldamodel.LdaModel(corpus=corpus, id2word=dictionary, num_topics=num_topics, update_every=0, chunksize=5000, passes=20)
#lda_model.save("lda_model")
lda_corpus = lda_model[tfidf_corpus]
#corpora.MmCorpus.serialize("lda_corpus.mm", lda_corpus)

print("\nTopics by Latent Dirichlet Allocation model")
topics_found_lda = lda_model.print_topics(num_topics=5, num_words=10)
all_topics = lda_model.print_topics(num_topics=50, num_words=10)

# print(topics_found_lda)

import re

counter = 1
for t in topics_found_lda:
    print("Topic #{} {}".format(counter, t))
    words = re.findall('"([^"]+)"', t[1])
    words = ' '.join(words)
    print(words)
    counter += 1

<gensim.interfaces.TransformedCorpus object at 0x10f87f5c0>
None

Topics by Latent Dirichlet Allocation model
Topic #1 (8, '0.000*"can" + 0.000*"say" + 0.000*"know" + 0.000*"like" + 0.000*"year" + 0.000*"one" + 0.000*"see" + 0.000*"look" + 0.000*"call" + 0.000*"right"')
can say know like year one see look call right
Topic #2 (14, '0.000*"like" + 0.000*"say" + 0.000*"one" + 0.000*"see" + 0.000*"people" + 0.000*"best" + 0.000*"make" + 0.000*"know" + 0.000*"time" + 0.000*"never"')
like say one see people best make know time never
Topic #3 (21, '0.000*"like" + 0.000*"year" + 0.000*"say" + 0.000*"know" + 0.000*"just" + 0.000*"one" + 0.000*"come" + 0.000*"think" + 0.000*"see" + 0.000*"people"')
like year say know just one come think see people
Topic #4 (12, '0.020*"hope" + 0.020*"wish" + 0.013*"also" + 0.013*"time" + 0.013*"year" + 0.013*"start" + 0.013*"see" + 0.013*"think" + 0.013*"like" + 0.013*"2016"')
hope wish also time year start see think like 2016
Topic #5 (42, '0.024*"thing" + 0.018*"year" + 0.018*"like" + 0.018*"weird" + 0.018*"best" + 0.018*"dark" + 0.012*"moment" + 0.012*"kind" + 0.012*"find" + 0.012*"lot"')
thing year like weird best dark moment kind find lot

In [150]:
topics = []
for t in all_topics:
    words = re.findall('"([^"]+)"', t[1])
    words = ' '.join(words)
    topics.append(words)
    

print(topics)
topics.extend(("Stories with actual words", "Number of subelements in stories with actual words", "Stories with lemmas", "Number of subelements in stories with lemmas"))
len(topics)

['think like say people can see come know best one', 'nowhere 911 miraculous share oh know see hunk like call', 'worst can best people refugee now know kind advocate like', 'one can say year also make know like come time', 'year U.S. one first world New 2015 look city York', 'make first look year now say flight planet board happen', 'worst refugee can come like best Supreme way woman plane', 'can like best year know say oh thing come see', 'can say know like year one see look call right', 'debut take almost ready big Pasadena float Rose Parade know', 'less physiology tense tear know year see time together hope', 'worst can woman people advocate refugee kind responsibility best like', 'hope wish also time year start see think like 2016', 'say look year like know can one make first right', 'like say one see people best make know time never', 'one know can year see back call say make look', 'like see year best think love know one say make', 'year like snow feel police best worst pope see problem', 'one people know now come year world see like make', 'bender oldest Princess grande year one mission Penn. back new', 'year one know come can time like call make first', 'like year say know just one come think see people', 'year people 4 new next keep news NBC security 5:00', 'teacher Victor want Billy achievement elementary Sandra grow another Whitney', 'one year know see look people say world police kill', 'one year see like say come world look people now', 'now place Patricia Stark 2016 York New know one just', 'morning CNN copter radio gyro reality Holly sport culture best', 'say one can think like also now right make know', 'rocket year can say one know thing first call best', 'like people right say think now know Humira one can', 'say face Trump call number milk now also can vote', 'know can say now like people call make one think', 'see best like movie think love life free call make', 'know oh see like call say look can one make', 'year photo Pope boy Francis make one look come new', 'Humira infection include treatment St. Jude symptom family moderate fight', 'say make year one now first back know can see', 'athlete bad worst football Ronda Rousey music trophy victory grateful', 'John hear catch middle madness hotel Klemack burn tower Cadiz', 'see like can year think know best say want come', 'know oh like see right look say never can ever', 'thing year like weird best dark moment kind find lot', 'one year can make say people now see look come', 'know like now can think people come look see never', 'people one year come many know like say see new', 'like see people now one think know come can make', 'best policy can Mutual Liberty year thing like next insurance', 'one know say see can people look like year make', 'year know like best see one say come call just']

54

In [151]:
lda_df = pd.DataFrame(columns=range(50))

for i in range(len(lemma_stories)):
    doc = lda_corpus[i]
    for top, prob in doc:
        lda_df.set_value(i, top, prob)
print(doc)

[(4, 0.89500598354454752)]

In [152]:
lda_df[-1] = stories
lda_df[-2] = lda_df[-1].apply(lambda x: len(x))
lda_df[-3] = lemma_stories # Not a good indicator
lda_df[-4] = lda_df[-3].apply(lambda x: len(x))
lda_df
# # Rows are the stories where -1 column contains the actual words that were used in the stories
# # Columns are the topics found in lda(the words are lemmas)

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,-1,-2,-3,-4
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,[Rocket],1,[rocket],1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[Faster, than, a, GYRO, copter, ,, more, power...",128,"[faster, gyro, copter, powerful, pizza, rat, h...",65
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.793474,NaN,NaN,"[Welcome, ., I, &apos;m, Tom, Foreman, ., We, ...",60,"[welcome, Tom, foreman, use, superhero, help, ...",19
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[It, was, a, year, of, firsts, ., I, think, a,...",54,"[year, first, think, lot, people, predict, lot...",22
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[The, worst, way, to, start, came, in, the, fi...",949,"[worst, way, start, come, first, day, January,...",424
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[Worst, advocate, for, world, peace, ,, Russia...",399,"[worst, advocate, world, peace, Russian, presi...",188
6,NaN,NaN,NaN,NaN,NaN,0.749253,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[And, in, the, Indian, Ocean, ,, as, sad, as, ...",24,"[indian, ocean, sad, discovery, part, miss, Ma...",9
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[The, flaperon, found, on, reunion, was, impor...",186,"[flaperon, find, reunion, important, confirm, ...",80
8,NaN,NaN,NaN,NaN,0.022555,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[We, have, many, more, bright, spots, ahead, ....",1446,"[many, bright, spot, ahead, come, Hollywood, s...",620
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.937036,NaN,NaN,NaN,NaN,"[No, one, slammed, into, the, headlines, Harde...",989,"[one, slam, headline, harder, Donald, Trump, a...",428
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[At, the, White, House, ,, President, Obama, w...",593,"[White, House, president, Obama, work, hard, n...",273
11,NaN,NaN,NaN,NaN,0.0316437,NaN,NaN,NaN,NaN,NaN,...,NaN,0.783352,NaN,NaN,NaN,NaN,"[When, it, comes, to, music, ,, take, it, to, ...",1139,"[come, music, take, bank, lunch, money, Lewis,...",543
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.938083,NaN,NaN,"[Plenty, of, things, caught, our, attention, o...",1091,"[plenty, thing, catch, attention, online, line...",473
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[2015, was, full, of, twists, ,, turns, and, t...",224,"[2015, full, twist, turn, tourmoil, sure, ad, ...",89
14,NaN,NaN,NaN,NaN,0.202781,NaN,NaN,NaN,NaN,NaN,...,NaN,0.70024,NaN,NaN,NaN,NaN,"[Breaking, news, coming, out, of, Germany, ,, ...",1513,"[break, news, come, Germany, course, good, nig...",732
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.118836,NaN,NaN,NaN,NaN,"[A, billionaire, ,, a, brain, surgeon, and, de...",2240,"[billionaire, brain, surgeon, democratic, soci...",1004
16,NaN,NaN,NaN,NaN,NaN,0.922243,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[We, visited, our, planetary, neighbors, in, 2...",455,"[visit, planetary, neighbor, 2015, invention, ...",209
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[Live, from, America, &apos;s, News, Headquart...",144,"[live, America, news, headquarters, Patricia, ...",74
18,NaN,NaN,NaN,NaN,0.497027,NaN,NaN,NaN,NaN,NaN,...,NaN,0.425047,NaN,NaN,NaN,NaN,"[Over, the, past, year, events, our, country, ...",1208,"[past, year, event, country, influence, many, ...",615
19,NaN,NaN,NaN,NaN,0.0112991,NaN,NaN,NaN,NaN,NaN,...,NaN,0.716764,NaN,0.122527,NaN,NaN,"[2015, had, celebrity, BREAK-UPS, ., Come, bag...",1180,"[2015, celebrity, break-up, come, bag, fall, g...",600
20,NaN,NaN,NaN,NaN,0.945336,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[2015, one, of, NASCAR, &apos;s, biggest, name...",989,"[2015, one, NASCAR, biggest, name, drive, sun,...",494
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[Finally, ,, a, look, at, three, of, the, year...",172,"[finally, look, three, year, powerful, photo, ...",87
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.100747,NaN,0.0111016,NaN,NaN,"[Here, she, is, now, ,, Ellen, Degeneres, ., T...",5206,"[now, Ellen, Degeneres, thank, hi, thank, than...",1916
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[Next, on, the, NBC, 4, News, at, 5:00, ,, kee...",23,"[next, NBC, 4, news, 5:00, keep, people, safe,...",14
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[A, towering, inferno, burns, a, hotel, in, Du...",26,"[tower, inferno, burn, hotel, Dubai, hear, Joh...",12
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.740738,...,NaN,NaN,NaN,NaN,NaN,NaN,"[And, we, &apos;ll, take, you, to, Pasadena, w...",20,"[take, Pasadena, Rose, Parade, float, almost, ...",9
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[I, &apos;ve, got, your, New, Year, &apos;s, o...",171,"[new, year, outlook, plus, three, chance, rain...",72
27,NaN,NaN,NaN,NaN,0.895006,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"[And, right, now, at, 5:00, ,, New, Year, &apo...",261,"[right, now, 5:00, new, year, Eve, security, E...",133

In [153]:

lda_df.loc[-1] = topics  # adding a row

lda_df.index = lda_df.index + 1  # shifting index

lda_df = lda_df.sort_index()
lda_df.to_csv('short_test.csv')